[versions]
lavalink-api = "4.1.1"
lavalink-server = "4.1.1"
lavaplayer = "2.2.4"
lavasearch = "1.0.0"
lavalyrics = "1.1.0"

[plugins]
lavalink = { id = "dev.arbjerg.lavalink.gradle-plugin", version = "1.1.2" }

[libraries]
lavaplayer = { group = "dev.arbjerg", name = "lavaplayer", version.ref = "lavaplayer" }
lavalink-server = { group = "dev.arbjerg.lavalink", name = "Lavalink-Server", version.ref = "lavalink-server" }
lavasearch = { group = "com.github.topi314.lavasearch", name = "lavasearch", version.ref = "lavasearch" }
lavalyrics = { group = "com.github.topi314.lavalyrics", name = "lavalyrics", version.ref = "lavalyrics" }
lavasearch-plugin-api = { group = "com.github.topi314.lavasearch", name = "lavasearch-plugin-api", version.ref = "lavasearch" }
lavalyrics-plugin-api = { group = "com.github.topi314.lavalyrics", name = "lavalyrics-plugin-api", version.ref = "lavalyrics" }