name: Build and Publish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

permissions:
  contents: write 
  packages: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          distribution: zulu
          java-version: 17
          cache: gradle

    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Generate build report
      if: always()
      run: ./gradlew build --scan
    
    - name: Upload build artifacts
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: lavabili-plugin.jar
        path: build/libs/*.jar
    
    - name: Upload Release Assets
      if: github.event_name == 'release'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/libs/*.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        omitNameDuringUpdate: true
        omitPrereleaseDuringUpdate: true

    - name: JitPack build info
      if: github.event_name == 'release'
      run: |
        echo "Release published: ${{ github.event.release.tag_name }}"
        echo "JitPack will auto-build via webhook"
        echo "Check build status: https://jitpack.io/com/github/${{ github.repository }}/${{ github.event.release.tag_name }}"